# Dependencies
markdown:         kramdown
highlighter:      pygments
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            La Faute à l'algo
tagline:          "Blame the Algorithm"
description:      "Qui se cache derrière l'algorithme ?<br /><a href=\"/eps/\">Voir tous les épisodes</a>."
meta:             "2098. Les Algorithmes ont pris le contrôle de notre société. Mais comment en sommes-nous arrivés là ? Voici quelques vidéos du futur pour prendre conscience du rôle grandissant des algorithmes dans nos vies, à l'origine de notre déchéance."
url:              http://madrobot.fr
baseurl:          /
atnl:             https://vimeo.com/showcase/10072326

author:
  name:           'Jill-Jênn Vie'
  url:            https://jill-jenn.net
  twitter:        jjvie

paginate:         5
paginate_path:    '/revue-de-presse/page:num/'

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jilljenn/madrobot
